### ISSUE TITLE
Idea: have everybody make announcements (not only admins)

### ISSUE THREAD

**Issue by 5a54a** [nextcloud/announcementcenter#103]
Would be great is there was an option for admins to enable everybody to make announcements. The announcement app could then be used as some sort of simple forum where everybody could post.

**Comment by nickvergessen** [comment]
The admin can select groups which are allowed to post announcements.
Just add a group which contains all users.

**Comment by tedmctedson** [comment]
Could we make it so only the person (or an admin) that wrote the message may delete it ? Not just any other person (like it is right now).
