### ISSUE TITLE
Feature Request: option to add images and highlight URLs in announcements.

### ISSUE THREAD

**Issue by DarthSlider** [nextcloud/announcementcenter#127]
Option to add images directly into announcement would be great.
Also, URLs are not clickable atm, so a user should copy paste it into its browser.

**Comment by Schmuuu** [comment]
We are currently working on it :)
https://github.com/nextcloud/announcementcenter/issues/74
https://github.com/nextcloud/announcementcenter/pull/125

So I guess this issue could be closed as "duplicate" of https://github.com/nextcloud/announcementcenter/issues/74

**Comment by DarthSlider** [comment]
Awesome, thanks!
Close it, please.
