### ISSUE TITLE
Announcements are NOT shown if the user profile language is set to Simplified Chinese

### ISSUE THREAD

**Issue by wenzhuoz** [nextcloud/announcementcenter#146]
### Steps to reproduce
1. Post an announcement.
2. Set the profile Language to 简体中文(Simplifed Chinese) in Settings.
3. The posted Announcements are gone.

### Expected behaviour
Announcements are shown if the profile language is Simplified Chinese.

### Actual behaviour
Announcements are not shown if the profile language is Simplified Chinese.

### Server configuration

**Operating system**: Ubuntu 16.04

**Web server:** Apache

**Database:** MySQL

**PHP version:** php7.0-fpm-7.0.33

**Nextcloud version:** (see Nextcloud admin page) 15.0.5

**Where did you install Nextcloud from:** tar.gz

**Comment by wenzhuoz** [comment]
Setting the personal Locale to Chinese(Simplified Han) 'zh_Hans' variants can fix the problem.

**Comment by nickvergessen** [comment]
Seems like all plurals are broken, so I reported this in the server:
https://github.com/nextcloud/server/issues/14627

As this seems to be an issue with l10n.js in core, I'm closing this one, as the app can do nothing about it.
