### ISSUE TITLE
Cannot delete announcement from announcementcenter 

### ISSUE THREAD

**Issue by Hell-o-Admin** [nextcloud/announcementcenter#150]
### Steps to reproduce
1. Create an announcement from announcementcenter and publish
2. got to announcementcenter
3. try to delete old announcement by clicking on the little trash bin (appears on mouse over)

### Expected behaviour
announcementcenter should delete the announcement from the sql-database and refresh the page view (then without to deleted announcement)

### Actual behaviour
announcementcenter reloads but the to be deleted accouncement is still there. also an exception InvalidFieldName appears in error log

### Server configuration

**Operating system**:
FreeBSD 11.2 (iocage)
**Web server:**
nginx 1.14.2_13
**Database:**
MariaDB 10.3.13
**PHP version:**
7.3.4_2
**Nextcloud version:** (see Nextcloud admin page)
16.0.0.9
**Where did you install Nextcloud from:**
Manual upgrade / download (zip file).

Here is a full log of the error (changed username and ip):

[announcementcenter_InvalidFieldNameException.txt](https://github.com/nextcloud/announcementcenter/files/3130792/announcementcenter_InvalidFieldNameException.txt)

There is a accouncement with 'announcement_id' 18 in table 'oc_announcements'. The table has the following columns:
| announcement_id | announcement_time | announcement_user   | announcement_subject                                      | announcement_message |

Creating new anncouncements works without errors.

Could it be because the correct column name is not 'id' but 'accouncement_id'?

Everything else does not seems relevant at the moment, but can be added on request.

**Comment by RailsViceRoads** [comment]
Same behaviour on my system. After each deletion request I find an error in the nextcloud log:

`Doctrine\DBAL\Exception\InvalidFieldNameException: An exception occurred while executing 'DELETE FROM `oc_announcements` WHERE `id` = ?' with params [16]: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'id' in 'where clause'`

**Comment by nickvergessen** [comment]
Anyone of you willing to test https://github.com/nextcloud/announcementcenter/pull/151/files

I did some quick testing here and it solves the issue.

**Comment by ApoRes1337** [comment]
It works for me with no Problems on NX16 and the latest Announcement Center App.

**Comment by RailsViceRoads** [comment]
It works 4 me 2. (NX16 16.0.0.9 and Announcement Center 3.5.0)

**Comment by nickvergessen** [comment]
Thanks for testing. 3.5.1 with the fix has been published in the appstore.

**Comment by Hell-o-Admin** [comment]
@nickvergessen Thank you very much. I wasn*t fast enough to test the patch but 3.5.1 fixed the error for me too.
