### ISSUE TITLE
several logs error

### ISSUE THREAD

**Issue by stratege1401** [nextcloud/announcementcenter#157]
Hello,

Using NC 16.0.3

log is complaining:

[jsresourceloader] Error: Could not find resource js/oc-backbone-webdav.js to load
GET /index.php/apps/announcementcenter/

[jsresourceloader] Error: Could not find resource vendor/select2/select2.js to load
GET /index.php/apps/announcementcenter/

[cssresourceloader] Error: Could not find resource vendor/select2/select2.css to load
GET /index.php/apps/announcementcenter/

**Comment by nickvergessen** [comment]
select2 is deprecated for 19, so it should be okay to switch it in 18

**Comment by TP75** [comment]
issue confirmed for NC 16.0.4.1 and  Announcement center 3.5.1

**Comment by nickvergessen** [comment]
This has been fixed in the latest 17 version.
Until then the log in the console is acceptable
