### ISSUE TITLE
app is broken on my NC 16.0.3. 

### ISSUE THREAD

**Issue by stratege1401** [nextcloud/announcementcenter#158]
when using app announcementcenter, i believe nextcloud_announcements should show a red-dot and display any annoucement!

When a Announcement is made, i have the annoucement shown in is own app, but not in nextcloud_announcement. no red dot, no text, no nothing....

might be link to bug nextcloud/nextcloud_announcements#41 , i cannot choose any groups, because dropdown list is not shown 

in nextcloud DB, 

SELECT * FROM `oc_announcements` is showing me all the annoucement made. the last id is 28. 19 was the last done before upgrade to NC 16.0.1 / then 16.0.2 then 16.0.3
SELECT * FROM `oc_announcements_groups` is showing everyone as no groups can be choosen from bug nextcloud/nextcloud_announcements#41 
SELECT * FROM `oc_notifications` show annoucement made before upgarde to 16.0.3, last objectid is 19.
SELECT * FROM `oc_activity_mq` the last annoucement  {"author":"nextadmin","announcement":19} is out of bound as the last annoucement id is 28 !!!

bad mojo for me

**Comment by nickvergessen** [comment]
Please make sure, your cron jobs are running correctly. That will generate the activity entries and the notifications (red dot in the top bar)

**Comment by stratege1401** [comment]
Hello @nickvergessen 


Checked https://docs.nextcloud.com/server/15/admin_manual/configuration_server/background_jobs_configuration.html
I am using cron now


checking `crontab -u www-data -l`

30 3 * * * /usr/bin/nice /usr/bin/php -f /var/www/html/occ preview:pre-generate -vvv > /var/log/preview.cron.log%/usr/bin/nice /usr/bin/php -f /var/www/html/occ preview:pre-generate -vvv > /var/log/preview.cron.log #NextcloudPreview

do i miss some jobs ??

**Comment by nickvergessen** [comment]
Yes, please add a new line with:
```
*/5  *  *  *  * /usr/bin/php -f /var/www/html/cron.php
```

**Comment by stratege1401** [comment]
hello @nickvergessen 

yes, of course, i forget that one !!!

Did fix it, please considered as closed, announcements working again !
