### ISSUE TITLE
Move database structure to migrations

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/announcementcenter#160]
The app is still using the old database.xml way.

Migrating with `occ migration:generate-from-schema announcementcenter 3007` should work fine.

**Comment by SLYtiger16** [comment]
@nickvergessen How would one fix this issue for a PR?

**Comment by nickvergessen** [comment]
With the command from the first post

**Comment by SLYtiger16** [comment]
seriously, just commit the generated file?

**Comment by nickvergessen** [comment]
Done via #204

**Comment by nickvergessen** [comment]
Sorry I forgot you did this already. I just did it as I had a go with it while I updated all shipped apps too.

**Comment by SLYtiger16** [comment]
No worries, thanks!
