### ISSUE TITLE
Wrong Link behind SVG-Image

### ISSUE THREAD

**Issue by krayzie0x10** [nextcloud/announcementcenter#165]
### Steps to reproduce
1. Open Nextcloud
2. Click on SVG-Image instead of the Text
3. Get redirected to "files" instead of "Announcement"

### Server configuration
**Operating system**:
Ubuntu 18.04
**Web server:**
Apache2
**Database:**
MariaDB
**PHP version:**
7.2
**Nextcloud version:** (see Nextcloud admin page)
16.0.4

**Comment by nickvergessen** [comment]
You mean in the header bar? Or a notification?

Can not reproduce the issue in either of those.
