### ISSUE TITLE
No Notification after Announcement

### ISSUE THREAD

**Issue by krayzie85** [nextcloud/announcementcenter#166]
### Steps to reproduce
1. Open Nextcloud
2. Make Announcement with Notification
3. Realize there is no notification

**Operating system**:
Ubuntu 18.04
**Web server:**
Apache2
**Database:**
MariaDB
**PHP version:**
7.2
**Nextcloud version:** (see Nextcloud admin page)
16.0.04

There is no notification when i trigger an Announcement. Shouldn't there be a red dot too?

**Comment by nickvergessen** [comment]
Did you run the cron jobs? Check `index.php/settings/admin` it should tell you when the last batch of background jobs was executed.

**Comment by kugiigi** [comment]
I also have this issue on my NC instance on Owncube. I remember it working before but recently it doesn't work and I'm not sure if it started when I upgraded to 16.0.5 or not. I'm using webcron and so far background jobs run successfully every 10 mins.

**Comment by nickvergessen** [comment]
Well with webcron there could still be a huge backlog in the database, can you look at the number of entries in the oc_jobs table?

**Comment by kugiigi** [comment]
Sorry but I have no idea how to check that and I'm also using a hosting service so I can only use Web OCC.

**Comment by kugiigi** [comment]
I still wasn't able to check the contents of oc_jobs but my observation is that when my webcron interval is 4 minutes, the announcement notification is delayed by 4 hours. When it's 2 minutes, the delay is 2 hours and 1 minute is 1 hour and so on.

**Comment by nickvergessen** [comment]
@kugiigi I would suggest to just switch to system cron then.

Also you might want to check which jobs are in your database, because it then looks like there are 60 jobs which are recurrent. Best is to ask for help in our forums: https://help.nextcloud.com/

But this is nothing the app can fix, so I will close this.
