### ISSUE TITLE
Improvements for comment

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/announcementcenter#17]
- [ ] Add unread indicator, if an announcement has unread comments (like in the file list)
- [x] Allow multi-line comment support: https://github.com/nextcloud/server/issues/942 => #45

**Comment by Schmuuu** [comment]
Another idea:
you could also implement the feature that came for comments in Nextcloud 13; to make links (URLs) clickable.
I expected that feature to be available for every area in Nextcloud where one can write comments, but in the announcement center it wasn't the case, URLs are kept as plain text. Would be nice to have it here as well :)
Clickable links in the announcement themself would be awesome as well of course.
