### ISSUE TITLE
Delete/hide comments

### ISSUE THREAD

**Issue by Shen** [nextcloud/announcementcenter#176]
### Steps to reproduce
1. post an announcement
2. post a comment to this announcement with another user

### Expected behaviour
the announcement-owner should be able to delete/hide unwanted/spam comments.

### Actual behaviour
the announcement-owner can only delete his own announcement to remove unwanted/spam comments.

**Nextcloud version:**
16.0.5.1

**Announcement Center version:**
3.5.1

**Comment by nickvergessen** [comment]
This is the same behaviour file comments have and I want to keep that in line. Otherwise we would need our own API and everything which is way too much effort at the moment
