### ISSUE TITLE
Center sends wrong/old server url

### ISSUE THREAD

**Issue by paskalito** [nextcloud/announcementcenter#178]
Hi I just sent my first notification

And in the emails that people get all the links to the nextcloud invalid.
That is because they point to an old adress of the instance. But that changed over a year ago.

So where does announcement center fetches that address?
how can i change that?
where should it maybe fetch that adress instead? (maybe the same as share files)

**Comment by nickvergessen** [comment]
Check your config/config.php the value `overwrite.cli.url`

**Comment by paskalito** [comment]
**oh wow thanks a lot. it was actually wrong there.!**
not really sure how this happened. - i just had a major problem with my instance for the last 2 months that i finally fixed. - in the process running occ maintenance:repair commands and such. (and a quick search implied that theese commands can change that value)
also strange that all the share links were still corrrect..
however thanks a lot im gonna try again. 🎉
