### ISSUE TITLE
add close button to comment sidebar

### ISSUE THREAD

**Issue by alexanderdd** [nextcloud/announcementcenter#180]
### Steps to reproduce
1. Open announcement center on a smartphone browser
1. Add a comment
1. Try to read next announcement

### Expected behaviour
You can close the comment sidebar with the typical "x" in top right corner.

### Actual behaviour
You can not close the comment sidebar. App is unusable. You have to reload the page to read other announcements.

**Nextcloud version:** 18.1

**App version** 3.7.0

**Comment by SLYtiger16** [comment]
Done with #203
