### ISSUE TITLE
Feature Request: Create User-Group additionally to admins  (with no admin rights)

### ISSUE THREAD

**Issue by hheinen** [nextcloud/announcementcenter#181]
I'd love the option to configure a user-group for allowing the use of this App. This App could this way be used as a Newsletter Application, with sending information via E-Mail to the Members. I do not want to grant admin priviliages to all the users that should be allowed to use this App. 

Thanks for your work!

**Comment by nickvergessen** [comment]
Check the admin settings. This is already possible
