### ISSUE TITLE
the subject of the annoucements sent to groups are not shown in the email

### ISSUE THREAD

**Issue by rodrigoabella** [nextcloud/announcementcenter#183]
### Steps to reproduce
1. post an announcement choosing a group  
2. run the cron job to announce the announcement:
docker exec --user www-data nextcloud_app_1 php -f cron.php > /dev/null 2>&1
3. execute the activity send-mails:
docker exec --user www-data nextcloud_app_1 php occ activity:send-mails 

### Expected behaviour
An email with the subject and body is received: it should says something like "\<user\> announced \<subject\> and \<body\>"

### Actual behaviour
An email without the subject and body is received: only it says "\<user\> posted an announcement"

### Server configuration

**Operating system**:
Ubuntu 18.04

**Database:**
SQLite

**Announcement center version:**
3.7.0

**Nextcloud announcements version:**
1.7.0

**Nextcloud version:**
Nextcloud 18.0.2

**Where did you install Nextcloud from:**
local with Docker

**List of activated apps:**

Enabled:
  - accessibility: 1.4.0
  - activity: 2.11.0
  - announcementcenter: 3.7.0
  - calendar: 2.0.2
  - cloud_federation_api: 1.1.0
  - cms_pico: 1.0.5
  - comments: 1.8.0
  - contacts: 3.2.0
  - dav: 1.14.0
  - deck: 0.8.0
  - external: 3.5.0
  - federatedfilesharing: 1.8.0
  - federation: 1.8.0
  - files: 1.13.1
  - files_pdfviewer: 1.7.0
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - firstrunwizard: 2.7.0
  - forms: 1.1.1
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - nextcloud_announcements: 1.7.0
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - ojsxc: 3.4.4
  - password_policy: 1.8.0
  - photos: 1.0.0
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - quicknotes: 0.2.3
  - recommendations: 0.6.0
  - richdocuments: 3.5.2
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - sociallogin: 2.4.5
  - spreed: 8.0.5
  - support: 1.1.0
  - survey_client: 1.6.0
  - systemtags: 1.8.0
  - tasks: 0.12.1
  - text: 2.0.0
  - theming: 1.9.0
  - theming_customcss: 1.5.0
  - twofactor_backupcodes: 1.7.0
  - updatenotification: 1.8.0
  - viewer: 1.2.0
  - workflowengine: 2.0.0
Disabled:
  - admin_audit
  - admin_notifications
  - encryption
  - files_external
  - user_ldap

**Nextcloud configuration:**

{
    "system": {
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost:8080",
            "192.168.254.*"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "sqlite3",
        "version": "18.0.2.2",
        "overwrite.cli.url": "http:\/\/localhost:8080",
        "installed": true,
        "app_install_overwrite": [
            "ojsxc",
            "admin_notifications"
        ],
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "ssl",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}

**Comment by nickvergessen** [comment]
I think this is fixed by https://github.com/nextcloud/activity/pull/437
Can you check it when 18.0.4 was released? (or apply the patch from the activity change manually?)

**Comment by rodrigoabella** [comment]
> I think this is fixed by [nextcloud/activity#437](https://github.com/nextcloud/activity/pull/437)
> Can you check it when 18.0.4 was released? (or apply the patch from the activity change manually?)

Thanks for the response nick!!
I'm going to test manually it with the last activity app version and I will tell you about the result

**Comment by rodrigoabella** [comment]
I tried to replace my activity module with the last version(2.12.0) but I couldn't.
I got a web browser error message: "The files of the app Activity (activity) were not replaced correctly. Make sure it is a version compatible with the server."

Do you know how to test that version?

**Comment by nickvergessen** [comment]
Ah, it's a shipped app. Maybe just wait for the 18.0.4 release (should happen around 23th april)

**Comment by rodrigoabella** [comment]
> Ah, it's a shipped app. Maybe just wait for the 18.0.4 release (should happen around 23th april)

Ok Joas, I will wait for that release.

**Comment by rodrigoabella** [comment]
> Ah, it's a shipped app. Maybe just wait for the 18.0.4 release (should happen around 23th april)

I have tested it in the latest version 18.0.4 and the issue continues, I'm receiving the email with body "<user> posted an announcement"
