### ISSUE TITLE
Add option to expire notifications

### ISSUE THREAD

**Issue by rullzer** [nextcloud/announcementcenter#187]
Often notifications are short lived. Like 'this intance will get updates tomorrow evening' etc.
It would make sense to be able to set a lifetime on the announcement. So that if the announcement is no longer valid the notifiations gets killed.

**Comment by nickvergessen** [comment]
I think it is there in the ... Menu already?

**Comment by rullzer** [comment]
I can't find it then.
I mean I can manually delete them. etc. but that is not reall what i wanna do ;)

**Comment by nickvergessen** [comment]
See #70 and #13

There should be a bell icon allowing to delete notifications

**Comment by rullzer** [comment]
O sure. But that would mean I have to do this manually every time.
My idea would be to allow optionally to set an expiration date for the announcement. After which the notification would get killed automatically (maybe even the announcement in general)

**Comment by Ramdane34** [comment]
YES it will be very interesting

**Comment by almereyda** [comment]
This seems to be an edge case of #385, where such events can be scheduled.
