### ISSUE TITLE
Wrong links in email notifications

### ISSUE THREAD

**Issue by Tranquillius** [nextcloud/announcementcenter#189]
My domain for the nextcloud installation differs from the domain of the email server. If a notification mail is send, the links created use the domain of the mail server. This results in broken links. Even the protocol type (http instead of https) is wrong.

Example: 
Nextcloud:
nextcloud.fancy-domain.de
E-Mail-Server (used in Nextcloud):
xxx@another-fancy-domain.de

Result:
Broken links in announcement email with icons and links referes to nextcloud installation at  nextcloud.another-fancy-domain.de doesn't exist.

**Comment by nickvergessen** [comment]
Please check your config.php especially: `overwrite.cli.url`

**Comment by Tranquillius** [comment]
Thanks, this config solved my issue!
