### ISSUE TITLE
Ads clear

### ISSUE THREAD

**Issue by Ramdane34** [nextcloud/announcementcenter#190]
Ads clear

Do you know why the ads are deleted automatically? Can we manage this parameter? If yes, how ?

**Comment by nickvergessen** [comment]
Sorry I don't understand what you mean.
Maybe you can add a screenshot?

**Comment by Ramdane34** [comment]
Thank you for your reply.
I would like to know how the advertisements are managed. How are they deleted?

**Comment by Ramdane34** [comment]
Is it possible to configure the lifespan of a notification?

**Comment by nickvergessen** [comment]
I'm not sure what you mean with ads?

There is a button on each announcement to remove the notifications

**Comment by nickvergessen** [comment]
See #187 

So I'm closing this.
