### ISSUE TITLE
Improve emails

### ISSUE THREAD

**Issue by Maxouxax** [nextcloud/announcementcenter#198]
This app is very good, but it could be even more.
Here's how:
Currently, when posting an announcement and choosing to create activities, the user receives an email. It's awesome ! But the email sent is basically useless.
Instead of just showing "An announcement has been posted!", you should actually post the announcement in the email.
I think it could be a big improvement.

Oh and also, I don't know if that's the case right now, but it would be great if the app could support Markdown. It allows administrators to style their announcement with a simple and effective tool.
And of course, translate the Markdown to HTML in the email so that we can actually see what the announcement looks like.

**Comment by SLYtiger16** [comment]
@Maxouxax I believe the email you receive is coming from the activities app not announcement center.

**Comment by Maxouxax** [comment]
Oh really ? I thought the announcement center app was simply "appending" an email to the queue (which is sent by the activity app, but the content is given by the announcement app).

So if it's the case, I need to create an issue on the activity app to change the emails I guess ?
And the markdown feature would be still great haha :)

**Comment by nickvergessen** [comment]
Well yes and no. Since I am or was the maintainer of both apps I know the issue.
It's just a matter of finding time to work on it.
Currently we only send activity emails which therefor only have a subject, but the plan is to have dedicated emails at some point.

**Comment by nickvergessen** [comment]
See #140 and #65
