### ISSUE TITLE
Only the last 5 announcements are fetched from "loadannouncements" on app load/refresh

### ISSUE THREAD

**Issue by SLYtiger16** [nextcloud/announcementcenter#201]
### Steps to reproduce
1. post more than 5 announcements
2. all announcements posted prior to refresh are shown
3. reload the page or navigate to the app after this

### Expected behaviour
I would expect to see all announcements

### Actual behaviour
Only the last 5 announcements are loaded

### Server configuration

**Operating system**:
Ubuntu 20.04
**Web server:**
Apache2
**Database:**
MariaDB
**PHP version:**
7.4
**Nextcloud version:** (see Nextcloud admin page)
19.0.0

**Comment by dirdi** [comment]
I do not think that the number of loaded announcements should be increased but instead more announcements should dynamically be loaded when one scrolls down and reaches the end of the announcements page.

**Comment by SLYtiger16** [comment]
@dirdi smart loading the announcements on scroll really would be the most efficient way of handling this, I think you are right.
