### ISSUE TITLE
Creating Announcements not working

### ISSUE THREAD

**Issue by SHSolution** [nextcloud/announcementcenter#252]
### Steps to reproduce
1. Open Announcements APP
2. Write an announcement
3. [Edit Options], Save Announcement

### Expected behaviour
I can choose the desired groups an set different options before saving the announcement.

### Actual behaviour
Group Field is not shown, so I cannot choose any group. Options and Save Button don't do anything

![image](https://user-images.githubusercontent.com/26604350/100663974-4d7ad900-3357-11eb-8696-e6695eef2257.png)

--> see browser log

## Server configuration detail

**Operating system:** Linux 5.4.0-54-generic #60-Ubuntu SMP Fri Nov 6 10:37:59 UTC 2020 x86_64

**Webserver:** Apache/2.4.38 (Debian) (apache2handler)

**Database:** mysql 10.5.8

**PHP version:** 

7.4.12
Modules loaded: Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, session, posix, Reflection, standard, SimpleXML, pdo_sqlite, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, apcu, bcmath, exif, gd, gmp, imagick, intl, ldap, memcached, pcntl, pdo_mysql, pdo_pgsql, redis, sodium, zip, Zend OPcache

**Nextcloud version:** 20.0.2 - 20.0.2.2

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

**Where did you install Nextcloud from:** Docker Hub; Docker Container behind nginx proxy (same behavior without proxy) 

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.6.0
 - activity: 2.13.3
 - announcementcenter: 4.0.0
 - bruteforcesettings: 2.0.1
 - calendar: 2.1.2
 - cloud_federation_api: 1.3.0
 - comments: 1.10.0
 - contacts: 3.4.2
 - contactsinteraction: 1.1.0
 - dashboard: 7.0.0
 - dav: 1.16.1
 - deck: 1.2.2
 - external: 3.7.1
 - federatedfilesharing: 1.10.1
 - federation: 1.10.1
 - files: 1.15.0
 - files_pdfviewer: 2.0.1
 - files_rightclick: 0.17.0
 - files_sharing: 1.12.0
 - files_trashbin: 1.10.1
 - files_versions: 1.13.0
 - files_videoplayer: 1.9.0
 - firstrunwizard: 2.9.0
 - forms: 2.0.4
 - groupfolders: 8.2.0
 - issuetemplate: 0.7.0
 - logreader: 2.5.0
 - lookup_server_connector: 1.8.0
 - mail: 1.7.0
 - nextcloud_announcements: 1.9.0
 - notes: 4.0.1
 - notifications: 2.8.0
 - oauth2: 1.8.0
 - password_policy: 1.10.1
 - photos: 1.2.0
 - privacy: 1.4.0
 - provisioning_api: 1.10.0
 - recommendations: 0.8.0
 - richdocuments: 3.7.10
 - serverinfo: 1.10.0
 - settings: 1.2.0
 - sharebymail: 1.10.0
 - spreed: 10.0.3
 - support: 1.3.0
 - survey_client: 1.8.0
 - systemtags: 1.10.0
 - tasks: 0.13.6
 - text: 3.1.0
 - theming: 1.11.0
 - twofactor_backupcodes: 1.9.0
 - updatenotification: 1.10.0
 - user_status: 1.0.1
 - viewer: 1.4.0
 - weather_status: 1.0.0
 - workflowengine: 2.2.0
Disabled:
 - admin_audit
 - encryption
 - files_external
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "htaccess.RewriteBase": "\/",
    "memcache.local": "\\OC\\Memcache\\APCu",
    "apps_paths": [
        {
            "path": "\/var\/www\/html\/apps",
            "url": "\/apps",
            "writable": false
        },
        {
            "path": "\/var\/www\/html\/custom_apps",
            "url": "\/custom_apps",
            "writable": true
        }
    ],
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "***REMOVED SENSITIVE VALUE***"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "20.0.2.2",
    "overwrite.cli.url": "http:\/\/host:8081",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "mail_smtpmode": "smtp",
    "mail_smtpauthtype": "LOGIN",
    "mail_sendmailmode": "smtp",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "465",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpsecure": "ssl",
    "mail_smtpauth": 1,
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "default_language": "de",
    "default_locale": "de_DE"
}
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** no

## Client configuration

**Browser:** Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36

**Operating system:** Linux Mint Cinnamon 20 (client)

## Logs

<details><summary>Web server error log</summary>

```
Insert your web server log here 
```
</details>

<details><summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

<details><summary>Browser log</summary>

index.js:46 No OC found
t.getLanguage @ index.js:46
jquery-migrate.min.js:2 JQMIGRATE: Migrate is installed, version 1.4.1
globals.js:60 jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
ie @ globals.js:60
4globals.js:60 $ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
ie @ globals.js:60
4globals.js:60 jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
ie @ globals.js:60
3globals.js:60 $ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
ie @ globals.js:60
script.js?v=5bc68524-6:42 **Uncaught TypeError: OCA.AnnouncementCenter.Comments.CommentsTabView is not a constructor**
    at Object.init (script.js?v=5bc68524-6:42)
    at HTMLDocument.<anonymous> (script.js?v=5bc68524-6:418)
    at l (jquery.js:3187)
    at Object.add [as done] (jquery.js:3246)
    at e.fn.init.m.fn.ready (jquery.js:3496)
    at script.js?v=5bc68524-6:417
globals.js:60 Handlebars is deprecated: please ship your own, this will be removed in Nextcloud 20
ie @ globals.js:60
session-heartbeat.js:97 session heartbeat polling started
2globals.js:60 $ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
ie @ globals.js:60
manifest:1 Manifest: property 'start_url' ignored, should be same origin as document.
</details>

**Comment by jonrsawyer** [comment]
I'm having the same problem. This is what I see on my Basic Settings page:

![image](https://user-images.githubusercontent.com/2525277/101221939-fb330400-3645-11eb-85c1-dd698f7feed5.png)

**Comment by nickvergessen** [comment]
That's the wrong app @jonrsawyer

**Comment by nickvergessen** [comment]
@SHSolution this looks like not all files where uploaded correctly. Can you check that?

**Comment by SHSolution** [comment]
Meanwhile I got it working. I assume that it was some configuration problem which prevented the app from correctly loading the required resources / information.

**Comment by Deuteu** [comment]
I'm encountering the same issue.
Moreover when going into Settings > Additional settings I got this error

> Uncaught TypeError: Cannot read properties of undefined (reading 'setupGroupsSelect')
>     at HTMLDocument.<anonymous> (admin.js?v=aafae745-8:27)
>     at l (jquery.js:3187)
>     at Object.add [as done] (jquery.js:3246)
>     at e.fn.init.m.fn.ready (jquery.js:3496)
>     at admin.js?v=aafae745-8:23
> (anonymous) @ admin.js?v=aafae745-8:27
> l @ jquery.js:3187
> add @ jquery.js:3246
> m.fn.ready @ jquery.js:3496
> (anonymous) @ admin.js?v=aafae745-8:23
