### ISSUE TITLE
Dashboard Announcement Widget keeps spinning for non Admin Users

### ISSUE THREAD

**Issue by greavette** [nextcloud/announcementcenter#268]
Nextcloud 20.0.4
Dashboard App version 7.0
Announcement Center 4.0

I've opened forum post regarding this issue:

https://help.nextcloud.com/t/dashboard-announcement-widget-keeps-spinning-not-showing-announcements/100697

I've added the Announcement Widget to my Dashboard and noticed that Admins on our nextcloud can see announements in the widget, but non Admin users only see a spinning circle on their widget like it's trying to load.  

Please advice what more information I can provide to help with this issue.  

Thank you.

**Comment by nickvergessen** [comment]
Can you press F12 to open the browsers console? I guess there should be a red error printed.
Also which browser are you using?

**Comment by nickvergessen** [comment]
Closing due to the lack of feedback
