### ISSUE TITLE
Fatal Log entry's "no app in context"

### ISSUE THREAD

**Issue by leuedaniel** [nextcloud/announcementcenter#328]
### Steps to reproduce
1. Fresh installation from NC 21.0.1
2. Install App announcement center
3. Log entry's each second

### Expected behaviour
No Fatal Log entry's because the app itself works.

### Actual behaviour
Log entry each minute:
`{"reqId":"ATi9G4CNV78koJ9O7zcn","level":4,"time":"2021-04-15T12:55:48+00:00","remoteAddr":"2a02:1205:5029:ca20:bd9a:104e:572f:9533","user":"37","app":"no app in context","method":"GET","url":"/apps/logreader/get?offset=0&count=50&levels=00001","message":{"Exception":"Error","Message":"Class 'OCA\\Comments\\AppInfo\\Application' not found","Code":0,"Trace":[{"file":"/var/www/nextcloud_hgv/apps/announcementcenter/lib/AppInfo/Application.php","line":64,"function":"load","class":"OC\\Comments\\Manager","type":"->"},{"file":"/var/www/nextcloud_hgv/lib/private/AppFramework/Bootstrap/FunctionInjector.php","line":68,"function":"registerCommentsEntity","class":"OCA\\AnnouncementCenter\\AppInfo\\Application","type":"->"},{"file":"/var/www/nextcloud_hgv/lib/private/AppFramework/Bootstrap/BootContext.php","line":52,"function":"injectFn","class":"OC\\AppFramework\\Bootstrap\\FunctionInjector","type":"->"},{"file":"/var/www/nextcloud_hgv/apps/announcementcenter/lib/AppInfo/Application.php","line":57,"function":"injectFn","class":"OC\\AppFramework\\Bootstrap\\BootContext","type":"->"},{"file":"/var/www/nextcloud_hgv/lib/private/AppFramework/Bootstrap/Coordinator.php","line":176,"function":"boot","class":"OCA\\AnnouncementCenter\\AppInfo\\Application","type":"->"},{"file":"/var/www/nextcloud_hgv/lib/private/legacy/OC_App.php","line":197,"function":"bootApp","class":"OC\\AppFramework\\Bootstrap\\Coordinator","type":"->"},{"file":"/var/www/nextcloud_hgv/lib/private/legacy/OC_App.php","line":137,"function":"loadApp","class":"OC_App","type":"::"},{"file":"/var/www/nextcloud_hgv/lib/base.php","line":979,"function":"loadApps","class":"OC_App","type":"::"},{"file":"/var/www/nextcloud_hgv/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud_hgv/lib/private/Comments/Manager.php","Line":1307,"CustomMessage":"Could not boot announcementcenterClass 'OCA\\Comments\\AppInfo\\Application' not found"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.128 Safari/537.36","version":"21.0.1.1","id":"607837d4b26cc"}`

### Server configuration
**Operating system**:
Linux Ubuntu 20.04.2
**Web server:**
Nginx
**Database:**
MariaDB
**PHP version:**
7.4.3
**Nextcloud version:** (see Nextcloud admin page)
21.0.1
**Where did you install Nextcloud from:
https://download.nextcloud.com/server/releases/nextcloud-21.0.1.zip
**Signing status:**

**List of activated apps:**

Enabled:
  - accessibility: 1.7.0
  - activity: 2.14.3
  - announcementcenter: 5.0.0
  - cloud_federation_api: 1.4.0
  - dav: 1.17.1
  - external: 3.8.1
  - federatedfilesharing: 1.11.0
  - files: 1.16.0
  - files_rightclick: 1.0.0
  - files_sharing: 1.13.1
  - files_trashbin: 1.11.0
  - files_versions: 1.14.0
  - files_videoplayer: 1.10.0
  - groupfolders: 9.0.0
  - login_notes: 0.4.0
  - logreader: 2.6.0
  - lookup_server_connector: 1.9.0
  - notifications: 2.9.0
  - oauth2: 1.9.0
  - onlyoffice: 6.3.0
  - privacy: 1.5.0
  - provisioning_api: 1.11.0
  - quota_warning: 1.10.0
  - serverinfo: 1.11.0
  - settings: 1.3.0
  - sharebymail: 1.11.0
  - suspicious_login: 4.0.0
  - theming: 1.12.0
  - twofactor_backupcodes: 1.10.0
  - updatenotification: 1.11.0
  - user_sql: 4.7.0-dev
  - viewer: 1.5.0
  - workflowengine: 2.3.0
Disabled:
  - admin_audit
  - comments
  - contactsinteraction
  - dashboard
  - encryption
  - federation
  - files_external
  - files_pdfviewer
  - firstrunwizard
  - nextcloud_announcements
  - password_policy
  - photos
  - recommendations
  - support
  - survey_client
  - systemtags
  - text
  - user_ldap
  - user_status
  - weather_status

**Nextcloud configuration:**

`{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.hgverwaltung.ch"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "21.0.1.1",
        "overwrite.cli.url": "https:\/\/cloud.hgverwaltung.ch",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "theme": "",
        "loglevel": 2,
        "maintenance": false,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "default_language": "de",
        "force_language": "de",
        "default_locale": "de-ch",
        "force_locale": "de-ch",
        "skeletondirectory": "",
        "knowledgebaseenabled": false,
        "updater.release.channel": "stable",
        "default_phone_region": "CH"
    }
}
`

**Are you using an external user-backend, if yes which one:** User SQL

### Client configuration
**Browser:**
Chrome
**Operating system:**
Win10
#### Nextcloud log (data/owncloud.log)
`{"reqId":"ATi9G4CNV78koJ9O7zcn","level":4,"time":"2021-04-15T12:55:48+00:00","remoteAddr":"2a02:1205:5029:ca20:bd9a:104e:572f:9533","user":"37","app":"no app in context","method":"GET","url":"/apps/logreader/get?offset=0&count=50&levels=00001","message":{"Exception":"Error","Message":"Class 'OCA\\Comments\\AppInfo\\Application' not found","Code":0,"Trace":[{"file":"/var/www/nextcloud_hgv/apps/announcementcenter/lib/AppInfo/Application.php","line":64,"function":"load","class":"OC\\Comments\\Manager","type":"->"},{"file":"/var/www/nextcloud_hgv/lib/private/AppFramework/Bootstrap/FunctionInjector.php","line":68,"function":"registerCommentsEntity","class":"OCA\\AnnouncementCenter\\AppInfo\\Application","type":"->"},{"file":"/var/www/nextcloud_hgv/lib/private/AppFramework/Bootstrap/BootContext.php","line":52,"function":"injectFn","class":"OC\\AppFramework\\Bootstrap\\FunctionInjector","type":"->"},{"file":"/var/www/nextcloud_hgv/apps/announcementcenter/lib/AppInfo/Application.php","line":57,"function":"injectFn","class":"OC\\AppFramework\\Bootstrap\\BootContext","type":"->"},{"file":"/var/www/nextcloud_hgv/lib/private/AppFramework/Bootstrap/Coordinator.php","line":176,"function":"boot","class":"OCA\\AnnouncementCenter\\AppInfo\\Application","type":"->"},{"file":"/var/www/nextcloud_hgv/lib/private/legacy/OC_App.php","line":197,"function":"bootApp","class":"OC\\AppFramework\\Bootstrap\\Coordinator","type":"->"},{"file":"/var/www/nextcloud_hgv/lib/private/legacy/OC_App.php","line":137,"function":"loadApp","class":"OC_App","type":"::"},{"file":"/var/www/nextcloud_hgv/lib/base.php","line":979,"function":"loadApps","class":"OC_App","type":"::"},{"file":"/var/www/nextcloud_hgv/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud_hgv/lib/private/Comments/Manager.php","Line":1307,"CustomMessage":"Could not boot announcementcenterClass 'OCA\\Comments\\AppInfo\\Application' not found"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.128 Safari/537.36","version":"21.0.1.1","id":"607837d4b26cc"}`

**Comment by leuedaniel** [comment]
After update to 21.0.2 same problem

**Comment by leuedaniel** [comment]
When i delete the line 64 in https://github.com/nextcloud/announcementcenter/blob/master/lib/AppInfo/Application.php it works.

**Comment by nickvergessen** [comment]
The problem is you have the comments app disabled.

I will check what we can do
