### ISSUE TITLE
Compatible with NC 10.0 ?

### ISSUE THREAD

**Issue by iGormilhit** [nextcloud/announcementcenter#33]
I tried to install the Annoucement Center with NC 10, and I'm not abled to. In the `appinfo/info.xml`, the dependency is still related to ownCloud server's version 9.2. I don't know if it's the source of the problem.

### Steps to reproduce
1. Install NextCloud 10.0.0
2. Install the Announcement Center
3. Go to the NC application management center
4. In the section of unactive applications

### Expected behaviour
The Announcement Center should be activable

### Actual behaviour
The Announcement Center isn't activable because "Server version 11 or higher is required."

### Server configuration
**Operating system**: Debian 7

**Web server:** Apache 2.2

**Database:** MySQL

**PHP version:** 5.6

**Nextcloud version:** 10.0

**Where did you install Nextcloud from:** From the official ZIP

**Signing status:**

No error have been found

**List of activated apps:**

```
Enabled:
  - activity: 2.3.2
  - admin_audit: 1.0.0
  - calendar: 1.3.3
  - comments: 1.0.0
  - contacts: 1.3.1.0
  - dav: 1.0.0
  - documents: 0.13.1
  - external: 1.2
  - federatedfilesharing: 1.0.1
  - federation: 1.0.1
  - files: 1.5.2
  - files_external: 1.0.2
  - files_pdfviewer: 0.8.1
  - files_sharing: 1.0.0
  - files_texteditor: 2.1
  - files_trashbin: 1.0.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - notes: 2.0.2
  - notifications: 0.3.0
  - password_policy: 1.0.0
  - provisioning_api: 1.0.0
  - serverinfo: 1.1.1
  - survey_client: 0.1.5
  - systemtags: 1.0.2
  - tasks: 0.9.3
  - templateeditor: 0.1
  - theming: 1.0.1
  - updatenotification: 1.0.1
  - workflowengine: 1.0.1
Disabled:
  - announcementcenter
  - encryption
  - files_accesscontrol
  - files_automatedtagging
  - files_retention
  - galleryplus
  - user_external
  - user_ldap
  - user_saml
```

**The content of config/config.php:**

```<?php
$CONFIG = array (
  'instanceid' => 'xxxxx',
  'passwordsalt' => 'xxxxxxxx',
  'datadirectory' => '/xxx/xxx',
  'dbtype' => 'mysql',
  'version' => '9.1.0.16',
  'dbname' => 'xxxxx',
  'dbhost' => 'xxxxx',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'xxxxx',
  'dbpassword' => 'xxxxxx',
  'installed' => true,
  'loglevel' => 0,
  'theme' => '',
  'maintenance' => false,
  'trusted_domains' => 
  array (
    0 => 'id-libre.org',
  ),
  'share_folder' => '/Shared',
  'knowledgebaseenabled' => true,
  'remember_login_cookie_lifetime' => 1296000,
  'session_lifetime' => 86400,
  'session_keepalive' => true,
  'forcessl' => true,
  'asset-pipeline.enabled' => false,
  'secret' => 'xxxxxx',
  'mail_smtpmode' => 'php',
  'mail_from_address' => 'xxx',
  'mail_domain' => 'xxxxx',
  'overwrite.cli.url' => '/xxxx',
  'trashbin_retention_obligation' => 'auto',
  'enable_previews' => true,
  'filelocking.enabled' => 'true',
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' => 
  array (
    'host' => 'xxxx',
    'port' => xxxx,
    'timeout' => 0,
  ),
);
```

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/... : No.

### Client configuration
**Browser:** Firefox 48

**Operating system:** Archlinux

**Comment by iGormilhit** [comment]
I've edited the `appinfo/info.xml`:

```
	<dependencies>
		<owncloud min-version="9.0" max-version="9.2" />
	</dependencies>
```
Then, I had to start again the `occ upgrade` script. And after that, I was able to activate the Annoucement Center, which seems to work fine.

**Comment by nickvergessen** [comment]
See https://github.com/nextcloud/announcementcenter/releases/tag/v2.0.0
Or https://help.nextcloud.com/t/announcement-center-discussion/2527
