### ISSUE TITLE
Tables and Some markdown syntaxes are not working 

### ISSUE THREAD

**Issue by elhananjair** [nextcloud/announcementcenter#331]
### Steps to reproduce
1. Write a table markdown on detail part of the announcement 

### Expected behaviour
Table format

### Actual behaviour
It shows the raw characters(such as |, ==)  that I have used when I wrote the details. 

### Server configuration

**Operating system**:
Linux Fedora 33
**Web server:**
Apache
**Database:**
PostgreSQL
**PHP version:**
7.4.16
**Nextcloud version:** (see Nextcloud admin page)
20.0.9
**Where did you install Nextcloud from:**
From Official Website

**Comment by nickvergessen** [comment]
I copied the sample from https://juliushaertl-vue-richtext.netlify.app/markdown.html
and it works quite nicely:
![Bildschirmfoto von 2021-04-20 10-21-04](https://user-images.githubusercontent.com/213943/115362810-35024280-a1c2-11eb-980b-3a69df2ea74f.png)

**Comment by elhananjair** [comment]
ohh yeah am sorry I didn't checked out recently, I have just tested that a while ago and didn't knew that it was fixed, thanks it works now.
