### ISSUE TITLE
Error when trying to post sth

### ISSUE THREAD

**Issue by deSpecialK** [nextcloud/announcementcenter#352]
### Steps to reproduce
1. Install AnnouncementCenter in our Instance
2. Go on AnnouncementCenter
3. Write an Announcement

### Expected behaviour
An Announcement should be posted

### Actual behaviour
The following error is thrown:
Doctrine\DBAL\Exception\InvalidFieldNameException: An exception occurred while executing a query: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'allow_comments' in 'field list'

### Server configuration

**Operating system**:
Ubuntu 20.04 LTS server on the web server
Ubuntu 20.04 LTS server on the database server

**Web server:**
nginx version: nginx/1.18.0 (Ubuntu)

**database
MariaDB 10.3

**PHP version:**
7.4

**Nextcloud version:** (see Nextcloud admin page)
21

**Where did you install Nextcloud from:**
apt

**Signing status:**
no subscription
```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```
No errors have been found.

**List of activated apps:**
Accessibility	1.7.0	Featured	
Activity	2.14.3	Featured	
Announcement center	5.0.0	Featured	
Auditing / Logging	1.11.0	Featured	
Brute-force settings	2.1.0	Featured	
Calendar	2.2.2	Featured	
Collaborative tags	1.11.0	Featured	
Comments	1.11.0	Featured	
Community Document Server	0.1.9		
Contacts	3.5.1	Featured	
Contacts Interaction	1.2.0	Featured	
Dashboard	7.1.0	Featured	
Deleted files	1.11.0	Featured	
External storage support	1.12.0	Featured	
Federation	1.11.0	Featured	
File sharing	1.13.1	Featured	
First run wizard	2.10.0	Featured	
LDAP user and group backend	1.11.0	Featured	
Log Reader	2.6.0	Featured	
Monitoring	1.11.0	Featured	
Nextcloud announcements	1.10.0	Featured	
Notifications	2.9.0	Featured	
ONLYOFFICE	7.0.2	Featured	
Password policy	1.11.0	Featured	
PDF viewer	2.1.0	Featured	
Photos	1.3.0	Featured	
Polls	1.8.3		
Privacy	1.5.0	Featured	
Ransomware protection	1.10.1		
Recommendations	1.0.0	Featured	
Right click	1.0.0	Featured	
Share by mail	1.11.0	Featured	
Support	1.4.0	Featured	
Tasks	0.13.6	Featured	
Text	3.2.0	Featured	
Theming	1.12.0	Featured	
Update notification	1.11.0	Featured	
Usage survey	1.9.0	Featured	
User status	1.1.1	Featured	
Versions	1.14.0	Featured	
Video player	1.10.0	Featured	
Weather status
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "xxxxx"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "21.0.2.1",
        "overwrite.cli.url": "https:\/\/xxxxx,
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "loglevel": 2,
        "maintenance": false,
        "default_phone_region": "DE",
        "memcache.local": "\\OC\\Memcache\\APCu"
    }
}
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
Active Directory
### Client configuration
**Browser:**
os / browser / client independant
**Operating system:**

#### Nextcloud log (data/owncloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

**Comment by nickvergessen** [comment]
Seems like you updated from a very old version and skipped a view updates in between.
Please run the following query manually:

```sql
ALTER TABLE `oc_announcements` ADD `allow_comments` SMALLINT(1) NULL DEFAULT '1'; 
```

**Comment by deSpecialK** [comment]
> Seems like you updated from a very old version and skipped a view updates in between.
> Please run the following query manually:
> 
> ```sql
> ALTER TABLE `oc_announcements` ADD `allow_comments` SMALLINT(1) NULL DEFAULT '1'; 
> ```

Many thanks, I was expecting such a problem - good to have a verification by an experienced person. Have a nice WE
