### ISSUE TITLE
Changes in Nextcloud 22 prevent the app from working (The appinfo/database.xml file is not longer supported. Used in w2g2)

### ISSUE THREAD

**Issue by EmilyLove26** [nextcloud/announcementcenter#379]
https://docs.nextcloud.com/server/latest/developer_manual/basics/storage/migrations.html

![image](https://user-images.githubusercontent.com/7028351/126883362-37d06d0e-983b-49bd-8ce4-f31340af13d2.png)

**Comment by nickvergessen** [comment]
The file doesn't exist anymore. Please make sure to update the apps correctly by deleting all old files first or using the build in app updater

**Comment by nickvergessen** [comment]
Also the note is shown for w2g2 not announcements

**Comment by EmilyLove26** [comment]
Ah my apologies. Somehow I landed here and I meant to post in https://github.com/newroco/W2G2/issues
