### ISSUE TITLE
Announcement Center not available for Nextcloud 22

### ISSUE THREAD

**Issue by greavette** [nextcloud/announcementcenter#387]
My Nextcloud Version - 22.1.1
Announcement Center version available - 5.0.0

Hello Team,

I've upgraded my Nextcloud from 21 to 21.1.1 and discovered that Announcement Center available in Nextcloud Apps is an untested app and not available.  

Are there plans to upgrade Announcement Center to work with Nextcloud 22?

Thank you.
![announcement_center](https://user-images.githubusercontent.com/5566606/133901212-2a59a793-f322-44f3-a5cb-169355de089f.jpg)

**Comment by nickvergessen** [comment]
Right, there is an alpha in the appstore since June. Just forgot to publish the final.
You can install it manually from https://apps.nextcloud.com/apps/announcementcenter for now.
The only difference will be the version number as there are no other changes.

**Comment by nickvergessen** [comment]
Done.
