### ISSUE TITLE
Didn't fire a notification

### ISSUE THREAD

**Issue by pierreozoux** [nextcloud/announcementcenter#40]
### Steps to reproduce
1. create a annoucement
2. as a non admin user, go to my cloud

### Expected behaviour
I think it should create a notification for the end user.

### Actual behaviour
No notifications were fired.

### Server configuration
**Operating system**: coreos / docker / debian

**Web server:** nginx

**Database:** mysql

**PHP version:** 5.6.25

**Nextcloud version:** 10

**Where did you install Nextcloud from:** docker official image

**Signing status:** good

**List of activated apps:**

```
Enabled:
  - activity: 2.3.2
  - announcementcenter: 2.0.0
  - bookmarks: 0.9.0
  - calendar: 1.3.3
  - comments: 1.0.0
  - contacts: 1.4.0.0
  - dav: 1.0.0
  - documents: true
  - federatedfilesharing: 1.0.1
  - federation: 1.0.1
  - files: 1.5.2
  - files_locking: true
  - files_pdfviewer: 0.8.1
  - files_sharing: 1.0.0
  - files_texteditor: 2.1
  - files_trashbin: 1.0.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - files_videoviewer: 0.1.3
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - mail: 0.5.3
  - notes: 2.0.2
  - notifications: 0.3.0
  - password_policy: 1.0.0
  - piwik: 0.1.0
  - provisioning_api: 1.0.0
  - registration: true
  - serverinfo: 1.1.1
  - survey_client: 0.1.5
  - systemtags: 1.0.2
  - tasks: 0.9.3
  - templateeditor: 0.1
  - theming: 1.0.1
  - user_sql: 2.2
  - workflowengine: 1.0.1
```

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

SQL

### Client configuration
**Browser:** firefox dev edition

**Operating system:** ubuntu

### Logs
nothing interesting there...

**Comment by nickvergessen** [comment]
Did you run teh cron job?
They are just queued, a cron job will perform the actual creation of the notifications.

**Comment by pierreozoux** [comment]
Thanks for the kind insight :)
