### ISSUE TITLE
announcements number limit

### ISSUE THREAD

**Issue by thadeu220** [nextcloud/announcementcenter#416]
hello!
the announcement center app does not show more than 7 announcements.
i already have more than 30 but it does only shows 7.
it has no option to change how much announcements to show!
how can we change this behavior?

steps to reproduce:
1. create more than 7 announcements
2. it will only show 7 announcements in the widget and in announcement page
3. there will be no button to change how much announcements must be shown to all users

nextcloud version: 22.2.3
PHP version: 7.4
server: litespeed enterprise
RAM: 16 GB RAM
Disk: 2 TB
O.S: CentOS 8

**Comment by elhananjair** [comment]
hey @thadeu220 I have mentioned this issue [here](https://github.com/nextcloud/announcementcenter/issues/385#issue-999337357).

**Comment by nickvergessen** [comment]
Closing as duplicate then
