### ISSUE TITLE
Pop out from dashboard does not open

### ISSUE THREAD

**Issue by mikebakke** [nextcloud/announcementcenter#425]
### Steps to reproduce
1. Publish an announcement
2. Click on the item in dashboard

### Expected behaviour
Expect the item to be opened in a new window

### Actual behaviour
Says the site is not reachable 

### Probable issue
I access my site with https://portal.mydomain.com/ but when the new tab is opened it also contains the actual port I am publishing so instead the URL is https://portal.mydomain.com:8445/apps/announcementcenter/?announcement=1

Access to the site is routed via haproxy which receives portal.mydomain.com:443 and forwards the request as https to xxx.xxx.xxx.xxx:8445 which is the IP and port for the docker instance. This works correctly with other pops from dashboard ie Talk and Calendar - they open https://portal.mydomain.com/app without :8445 as expected.

If I edit the failed URL in the new tab to remove :8445 it opens correctly.

#### Server
Docker running on Debian 11 - Nextcloud installed from official nextcloud 23.0 image talking to external myqsl db

**Comment by nickvergessen** [comment]
We only create a relative link
https://github.com/nextcloud/announcementcenter/blob/master/src/views/Dashboard.vue#L54

So the problem seems to be with your general Nextcloud or server configuration

**Comment by mikebakke** [comment]
ok I see the code thanks. I had assumed it was my somewhat convoluted setup because no-one else has the issue but was confused because other nextcloud official apps pop-out with no issue.

I will try to streamline config but I'm quite constrained by the use cases.

Rgds
