### ISSUE TITLE
Disabled users are notified about new announcements by e-mail

### ISSUE THREAD

**Issue by dirdi** [nextcloud/announcementcenter#478]
### Steps to reproduce
1. Go to https://nc.url/settings/users
2. Click "+ New user" button and create a test-user with valid e-mail address
3. Click "... > x Disable user" to disable the test-user
4. Go to https://nc.url//apps/announcementcenter/ and create a new announcement
5. The disabled test-user will receive a notification e-mail about the new announcement.

### Expected behaviour
Disabled users should never receive e-mails.

### Actual behaviour
Disabled users receive notifications about new announcements.

### Server configuration

**Operating system**: Linux 5.10.0-14-amd64 x86_64

**Web server:** Apache

**Database:** mysql 10.5.15 

**PHP version:** 8.0.20

**Nextcloud version:** Nextcloud Hub II (23.0.3)

**Where did you install Nextcloud from:** Archive file (https://download.nextcloud.com/server/releases/latest.zip)

**Signing status:**

```
No errors have been found.
```

**List of activated apps:**

```
Accessibility 1.9.0
Activity 2.15.0
Announcement center 6.3.0
Brute-force settings 2.4.0
Calendar 3.3.1
Collaborative tags 1.13.0
Comments 1.13.0
Contacts 4.1.1
Contacts Interaction 1.4.0
Deleted files 1.13.0
File access control 1.13.0
File sharing 1.15.0
Files automated tagging 1.13.0
Group folders 11.1.4
Impersonate 1.10.0
Log Reader 2.8.0
Monitoring 1.13.0
Notifications 2.11.1
Password policy 1.13.0
PDF viewer 2.4.0
Photos 1.5.0
Polls 3.6.1
Privacy 1.7.0
Right click 1.2.0
Talk 13.0.6
Text 3.4.1
Theming 1.14.0
Update notification 1.13.0
User status 1.3.1
Versions 1.16.0
Video player 1.12.0
```

**Nextcloud configuration:**

```
*nothing special*
```

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 101.0.1 (64-bit)

**Operating system:** Linux hostname 5.17.0-1-amd64 #1 SMP PREEMPT Debian 5.17.3-1 (2022-04-18) x86_64 GNU/Linux

#### Nextcloud log (data/owncloud.log)
```
*no errors*
```

#### Browser log
```
*no errors*
```

**Comment by nickvergessen** [comment]
Want to test the patch from https://github.com/nextcloud/announcementcenter/pull/480 ? :)

**Comment by dirdi** [comment]
@nickvergessen thank you for the fast fix. I was only today able to test the fix today and confirm that it fixes the issue.
