### ISSUE TITLE
Getting two emails for one announcement 

### ISSUE THREAD

**Issue by elhananjair** [nextcloud/announcementcenter#487]
### Steps to reproduce
1. Go to announcement app
2. write content of an announcement 
3. Announce it 

### Expected behaviour
For that announcement I should get one email, with the title and content of the post 

### Actual behaviour
I am getting first an email which contains only the title of announcement and another email containing both the title and the content

**Comment by nickvergessen** [comment]
The one with title only is the generic activity email. You can disable it in the posting options and admin settings
