### ISSUE TITLE
Only generate notifications for users that have already logged in

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/announcementcenter#49]
Ref https://github.com/nextcloud/server/issues/1889

If they never logged in, they also didn't set up any client, so it makes no sense.

**Comment by harry-7** [comment]
I would like to work on this issue. It would be great if you help me how to start with it

**Comment by nickvergessen** [comment]
Currently you have to checkout this branch on the server:
https://github.com/nextcloud/server/pull/1888

The first step is then to use `callForSeenUsers` instead of `callForAllUsers` in
https://github.com/nextcloud/announcementcenter/blob/8635f02696f7c4ac9811ca4a28fd6bca0992fbf6/lib/BackgroundJob.php#L143-L143

The second step is to make this also work when posting an announcement for a group. Therefor in the foreach at https://github.com/nextcloud/announcementcenter/blob/8635f02696f7c4ac9811ca4a28fd6bca0992fbf6/lib/BackgroundJob.php#L171-L171
a comparison of `$user->getLastLogin()` is needed.

Sounds good?

**Comment by harry-7** [comment]
@nickvergessen Should I wait for the branch to be committed ? If not how can I checkout that branch. I already forked the repo and cloned it

**Comment by nickvergessen** [comment]
> I already forked the repo and cloned it

The Nextcloud server repo as well? If not follow:
https://docs.nextcloud.com/server/11/developer_manual/general/devenv.html

Otherwise in your server repository do:
```
git fetch origin downstream-26361
git checkout -b downstream-26361 origin/downstream-26361
```

That's it.

**Comment by nickvergessen** [comment]
#52 has been merged, closing.

Thanks @harry-7 again!
