### ISSUE TITLE
No mail dispatch of the announcement

### ISSUE THREAD

**Issue by MANFahrer-GF** [nextcloud/announcementcenter#584]
I have a problem, I write an announcement to a group but no mails are sent.

nextcloud itself sends mails.

Netcloud Version: nextcloud all in one Version 4.0.1
Nexcloud: 25
Announcement Center: 6.4.0

**Comment by nickvergessen** [comment]
Are your cron jobs running?

**Comment by MANFahrer-GF** [comment]
Yes 
![cloud](https://user-images.githubusercontent.com/29804595/210533695-271963aa-5544-4c8e-bda3-76a558484929.PNG)

**Comment by nickvergessen** [comment]
Is there anything in your nextcloud.log file?

**Comment by MANFahrer-GF** [comment]
the nextcloud.log is empty and at the AIO no conspicuousness and under logs in the Nextcloud also nothing

**Comment by MANFahrer-GF** [comment]
If I send an announcement for all, it will be sent out, but if I restrict it to one group, no mail will be sent out.

**Comment by MANFahrer-GF** [comment]
Ok I found out that the mails are sent, but I as admin / sender do not receive any. I am also a member of the group

**Comment by nickvergessen** [comment]
The author of the announcement does not receive an email about their own action yes.
That's currently the expected behaviour.

**Comment by MANFahrer-GF** [comment]
Thanks - then everything goes great and know it now :-)
