### ISSUE TITLE
Database error when running migration 6003Date20220505000000 for app announcementcenter

### ISSUE THREAD

**Issue by solracsf** [nextcloud/announcementcenter#598]
### Steps to reproduce
1. `occ app:enable announcementcenter`
2. or install from WebUI (same error)

### Expected behaviour
App is installed

### Actual behaviour
```
# occ app:enable announcementcenter
Database error when running migration 6003Date20220505000000 for app announcementcenter
There is no table with name 'nextcloud.oc_announcements' in the schema.
```

### Server configuration

**Operating system**:

**Web server:** Apache 2.4

**Database:** MariaDB 10.6

**PHP version:** 8.1

**Nextcloud version:** (see Nextcloud admin page) 25.0.2

**Comment by nickvergessen** [comment]
Seems like the table was manually deleted while the app was still installed?

I would suggest to remove all entries from `oc_migrations` with app id set to `'announcementcenter'`, make sure there is no entry in `oc_appconfig` with that app id and then retry to enable it.
