### ISSUE TITLE
More prominent appearance of new announcements

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/announcementcenter#6]
We send notifications out per default since 1.2 version. But it would be nice,
if they could also be displayed as a pop-up (like the first-run-wizard, etc.)

Requested by @aspdye and @vain90 in https://github.com/owncloud/announcementcenter/issues/49

**Comment by amarlearning** [comment]
@nickvergessen Is anyone working on this ?
I like to work on this!

**Comment by nickvergessen** [comment]
Not yet, feel free to

**Comment by amarlearning** [comment]
@nickvergessen hey, can you help me in finding the documentation for setting up this app locally ?

**Comment by nickvergessen** [comment]
You need to install Nextcloud from git, see:
https://docs.nextcloud.com/server/11/developer_manual/general/devenv.html and 
https://docs.nextcloud.com/server/11/admin_manual/installation/source_installation.html

Afterwards check out this app into the `apps/` folder.

However, when you don't know how to set up the dev environment, maybe this issue is not the right thing for you to start with.
Better have a look at one of the starter issues: https://github.com/nextcloud/announcementcenter/issues?q=is%3Aissue+is%3Aopen+label%3A%22starter+issue%22

**Comment by nickvergessen** [comment]
I think for now the dashboard of Nextcloud 20 is good enough, so I will close this
