### ISSUE TITLE
Every announcement triggers 2 mail notifications

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/announcementcenter#637]
### Steps to reproduce
1. An admin announces something
2. You get email notifications

### Expected behaviour
1 email per announcement.

### Actual behaviour
2 emails per announcement – one via the app, one via the Nextcloud notification service:
![image](https://user-images.githubusercontent.com/925062/233124936-b79684e7-1896-46ef-ac97-fd93110388ec.png)

### Server configuration
Our current cloud.nc

**Comment by nickvergessen** [comment]
One is the activity email, the other one is the email from the app.
Activity email is off and not changable:
https://github.com/nextcloud/announcementcenter/blob/master/lib/Activity/Setting.php#L88-L96

Can you check if that box is ticked for you by accident (like it is for me) at …/settings/user/notifications

I guess that is a legacy state from the old times where it was open and enabled by default (from https://github.com/nextcloud/announcementcenter/pull/467 ) and not cleaned up, so it's still triggering

**Comment by jancborchardt** [comment]
Yup, state is on for both Mail and Push, for mail not changeable too:
![image](https://github.com/nextcloud/announcementcenter/assets/925062/17be5189-bb43-4c3c-b0d5-fa1961113e09)
