### ISSUE TITLE
[Feature request] preschedule accouncements

### ISSUE THREAD

**Issue by HB9HIL** [nextcloud/announcementcenter#677]
I would like to suggest implementing a way to schedule announcements in advance. This would allow announcements to be planned ahead of time to make organizing events easier. Has such a function ever been discussed?

I'm thinking of an additional option like "Publish immediately" or "Publish later" with a possibility to choose a date and time.

**Comment by mwinkens** [comment]
related #187 (because both require a cronjob and an extra table entry)
