### ISSUE TITLE
Not all users receives Mail notification

### ISSUE THREAD

**Issue by LuisCalzado** [nextcloud/announcementcenter#756]
### Steps to reproduce
1. Create any announcement
2. Send mail notification

### Expected behaviour
All users who can see the announcement should recibe mail notification.

### Actual behaviour
Just 21 random users of 100 recibe the mail notification.
Users who do not receive these emails when the announcement is for everyone, they receive them when the number of recipients is smaller, such as when filtered by groups.
We already contact with mail server distributor and we have not recipients limitation for massive mails.

**Comment by nickvergessen** [comment]
Anything in the log file?

**Comment by LuisCalzado** [comment]
Hello, i have done a test sending an announcement to a little group and find 0 errors in logs, cron do the job correctly, 
when I make an announcement to everyone will see if there are any errors. It sems like cron job works okey, but in the job are missing mails. Sorry for the delay.

**Comment by LuisCalzado** [comment]
hello, its fixed, it was a distributor limitation.
