### ISSUE TITLE
no notification - perhaps user_saml ?

### ISSUE THREAD

**Issue by adrienfr44** [nextcloud/announcementcenter#76]
Hi,
It's difficult to describe my problem.

I install new nextcloud 11.02. I create 3 users in standard mode (in user management panel > technical : users created in table ocs_users in database). With this 3 users, no problem with annoucementcenter and notification (write an annoucement for everyone or for group > notification ok).
Next, i plug the module auth sso/saml (user_saml). All users connected with this mode  (ln my case, 20 users auto-create with their first connection > technical : users created in table ocs_users_saml) **don't receive notification** (tehnical : BackgroundJob (action notify) don't create a sql-insert for this users in table ocs_notification)

I need help. I am available to try to make tests to better define the problem and find a specific case of reproduction. 

### Steps to reproduce
1. install nextcloud / create users in standard mode (users management panel) / activate notification module and annoucementcenter module
2. plug user_saml module (https://docs.nextcloud.com/server/11/admin_manual/configuration_server/sso_configuration.html) and connect (auto-create) other users with this module.
3. create an annoucement for everyone (or groupe) with notification option activated

### Expected behaviour
notification for all users

### Actual behaviour
notification only for users created in standard mode

### Server configuration
debian 8

**Web server:**
apache

**Database:**
mysql

**PHP version:**
PHP 5

**Nextcloud version:** (see Nextcloud admin page)
11.02

**Comment by nickvergessen** [comment]
Hmm actually we are looping over all users that already logged in at least once:
https://github.com/nextcloud/announcementcenter/blob/master/lib/BackgroundJob.php#L145

This code is used in many other places as well. Please confirm that the users logged in once, before posting an announcement. When that is the case, there is a bug in the server code and I will move the ticket and have a deeper look.

**Comment by adrienfr44** [comment]
Hi
Tks for this informations.

I check this point : "users that already logged in at least once" ; "Please confirm that the users logged in once"

sudo -u www-data php occ user:lastseen  <login>

result with user created by database OK : "<login> last login: 08.03.2017 21:44"

result with user created by saml KO (Yet users frequently connect and use my nextcloud) : "User does not exist"

i use the module user_saml mode production (version 1.2.2) with nextcloud 11.02 ...

:(
ps: no trace bug/issue/other about this in https://github.com/nextcloud/user_saml

**Comment by nickvergessen** [comment]
Can you please add an issue in the user_saml repo, because that seems to be an issue with that app then.

**Comment by adrienfr44** [comment]
ok tks. i do it.

ps nick : https://help.nextcloud.com/t/last-login-says-never-which-is-wrong/2616
