### ISSUE TITLE
Allow Users to change their mail behaviour

### ISSUE THREAD

**Issue by b90g** [nextcloud/announcementcenter#761]
`	public function canChangeMail(): bool {` is:
https://github.com/nextcloud/announcementcenter/blob/3a2fe675eed8f70b56c7453fb9d61685c5c10ab6/lib/Activity/Setting.php#L88

And even in the admin server default for new users its not possible to change it:
YOUR-SERVER.TDL/index.php/settings/admin/notifications

Is there a reason for this decision?

I saw the admin-setting in general to send Emails or not: ( index.php/settings/admin/additional )
https://github.com/nextcloud/announcementcenter/blob/3a2fe675eed8f70b56c7453fb9d61685c5c10ab6/lib/Settings/Admin.php#L55

**Comment by svenseeberg** [comment]
Interestingly, the setting seems to be deactivated by default (no check mark), but users do receive e-mails.

**Comment by nickvergessen** [comment]
The `…` button next to `Announce` on the form has an email checkbox:
https://github.com/nextcloud/announcementcenter?tab=readme-ov-file#announcement-center

The email option of activity was only introduced after announcements had it's emails and the activity would not contain the actual message, but only the headline. So we agreed that a dedicated "full" email would be better then the activity one.

**Comment by b90g** [comment]
Thanks for clarifying as i understand announcements can go into:
- the activity app  where its shown on the feed.
- the notification app where ONLY PUSH is available and selectable
- and email which is done regardless of the notification settings and can be handled differently on each announcement via `...`-Menu next to the  announcement button.
