### ISSUE TITLE
Ad open new window... where in the code ?

### ISSUE THREAD

**Issue by Tirguy** [nextcloud/announcementcenter#768]
Hello,

I'd like to prevent clicking on an ad in the Dashboard Widget and opening a new window : what part of the code could I modify to prevent a new window from opening ? 

Eventually, I'd like to open a modal window displaying the ad content, without it opening a new window.

Thank you for any help, guidance or ideas you may have.

Thierry

**Comment by nickvergessen** [comment]
It's part of the UI provided by the dashboard component in server inside compiled JS.
It's not easily changable/patchable:
https://github.com/nextcloud-libraries/nextcloud-vue/blob/master/src/components/NcDashboardWidgetItem/NcDashboardWidgetItem.vue#L35
