### ISSUE TITLE
announcement visibility mechanism

### ISSUE THREAD

**Issue by adrienfr44** [nextcloud/announcementcenter#77]
Nextcloud 11.0.2 mode production / announcementcenter 3.0.0 (and module user_ldap for optional info)

Users/Groups : 
user1 in ADMIN group
user2 in TEST group

-----------------------------
1/ In admin panel, only ADMIN group have right to create announcement
2a/ user1 create announcement1 - visibility ADMIN group
2b/ user1 create announcement2 - visibility TEST group

Result in Announcement interface:
- user1 see announcement1 and annoucement2 + the form for create announcement
- user2 see announcement2 only
>> This seems OK !?

------------------------------------------------
3/ In admin panel, now we add TEST group have right to create announcement

Result in Annoucement interface:
- user1 see announcement1 and annoucement2 + the form for create announcement
- user2 see announcement1 and annoucement2 + the form for create announcement
>> This seems incorrect !? user2 should see  annoucement2 + the form for create announcement ; but should not see annoucement1 ?

**Comment by nickvergessen** [comment]
Well the groups that are allowed to post are somewhat like admin groups and can currently see all announcements. Otherwise someone could post an announcement without being able to see it later on for editing, commenting or deleting

**Comment by adrienfr44** [comment]
ok tks for this precision Nick.
