### ISSUE TITLE
Announcement for admin not possible

### ISSUE THREAD

**Issue by Jhoecker24** [nextcloud/announcementcenter#800]
### Steps to reproduce
1. login NEXTCLOUD
2. click Announcement button
3.page doesn't show input box for entering announcements nor das ist show older announcements
4.

### Expected behaviour
should show input box and older announcements

### Actual behaviour
page doesn't show input box for entering announcements nor das ist show older announcements

### Server configuration

**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)

**Where did you install Nextcloud from:**

**Signing status:**

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Browser:**

**Operating system:**

#### Nextcloud log (data/owncloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

**Comment by nickvergessen** [comment]
Please provide more information, like which version of Nextcloud you use, which version of the app, how you installed it and maybe a screenshot of the page you see.

**Comment by Enigma2024** [comment]
same problem:
using Nextcloud Hub 8 (29.0.4)
I installed announcementcenter in the "Apps" admin-menu, announcement center version 6.8.1
I use my webbrowser for entering announcements, but there is no input box

**Comment by nickvergessen** [comment]
Please check if your browser has a AdBlocker that blocks it

**Comment by Enigma2024** [comment]
I stopped the AdBlocker, but there is still no input box
