### ISSUE TITLE
Idea: Allow other groups then Admin to send Announcements

### ISSUE THREAD

**Issue by SysGreg** [nextcloud/announcementcenter#81]
Hi. 

1.It would be great to allow selectable groups to send announcements, not only admin groups. 
2. As further development  additionally to above allow group admins to send to members.
For example if non admin user "X" is Admin for group "My Users" he/she would be able to send messages to members of his group.

Thanks for consideration
Greg

**Comment by nickvergessen** [comment]
See the additional settings in the admin settings
