### ISSUE TITLE
Move scheduling and deletion to `…` menu

### ISSUE THREAD

**Issue by mwinkens** [nextcloud/announcementcenter#820]
follow up of #767

**Comment by mwinkens** [comment]
@nickvergessen I don't know how to do this, since the `NcDateTimePicker` is not an `NcActions` component

**Comment by nickvergessen** [comment]
Best idea I have would be to copy what Talk does when setting a reminder on a chat message:
https://github.com/nextcloud/spreed/blob/main/src/components/MessagesList/MessagesGroup/Message/MessageButtonsBar/MessageButtonsBar.vue#L62

**Comment by mwinkens** [comment]
Apparently I can put a `NcDateTimePicker` there, I thought I was causing the message in #846
