### ISSUE TITLE
Announcementcenter not visiable in Beta 12?

### ISSUE THREAD

**Issue by brtptrs** [nextcloud/announcementcenter#83]
### Steps to reproduce
1. Install NC 12 beta
2. Activate announcementcenter

### Expected behaviour
Admin should be able to make announcements

### Actual behaviour
No link to the app seems to be available

### Server configuration
Ubuntu 16.04

**Operating system**:
Ubuntu 16.04

**Web server:**
Apache

**Database:**

**PHP version:**
7.0

**Nextcloud version:** (see Nextcloud admin page)
12 beta 3

**Comment by nickvergessen** [comment]
See #82 i have to release a new version. But i will do it this week

**Comment by brtptrs** [comment]
Thanks. Sorry I missed that issue.

**Comment by nickvergessen** [comment]
Published it: https://apps.nextcloud.com/apps/announcementcenter
