### ISSUE TITLE
disable notifications via occ

### ISSUE THREAD

**Issue by DanScharon** [nextcloud/announcementcenter#839]
First of all thank you so much for implementing the `occ` commands with the latest release! This is extremely helpful for us ❤️ 

The only puzzle piece missing for us would be the possibility to also disable notifications of a specific announcement via `occ`. In many cases we don't want to actually delete the whole announcement after certain while but just disable the notifications that we had set when creating the announcement.
This is already possible in the gui but it would be really helpful for us if we could also do this via `occ`.

Thank you!

**Comment by nickvergessen** [comment]
Noticed the same :D

**Comment by mwinkens** [comment]
assign self
