### ISSUE TITLE
Change "Visibility" field in announcement creation

### ISSUE THREAD

**Issue by Hussam92** [nextcloud/announcementcenter#850]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Feature request: Change UI component of "Visibility" field in announcement creation

Nextcloud 9 (30.0.0)

For new users it might be confusing to change the visibility of an Announcement while creating. Its hidden behind the 3 dots.

I believe it is a crucial feature and I suppose it is worth having it's own row. I will provide screenshots.

**Additional context**
User can write announcements for groups they are not member of. I will create a separate bug ticket

CURRENT
![image](https://github.com/user-attachments/assets/603e8c84-26ee-4e9d-a442-659fb5215ae1)

WISH
![image](https://github.com/user-attachments/assets/a04d1f67-a6d3-479c-9f3f-e5c8cf42f731)

**Comment by Hussam92** [comment]
Take it out of the 3 dots, move it to its own row. The 3 dots will only have checkboxes (permissions)
![image](https://github.com/user-attachments/assets/10a4280e-f7d2-4826-a847-b6895395466b)

**Comment by nickvergessen** [comment]
In the upcoming version the 2 previously shown options are also moved into the … menu. This is currently the expected design
