### ISSUE TITLE
Users are able to write Announcements FOR GROUPS THEY ARE NOT member of.

### ISSUE THREAD

**Issue by Hussam92** [nextcloud/announcementcenter#851]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

### Steps to reproduce
1. Sign in as Administrator or someone with the ability to write an Announcement (see Extra Settings -> Groups who can write Announcement)
2. Make sure a group exists which you are not member of
3. Write a new Announcement without submitting
4. Select Groups which will receive announcement
5. You will see the group listed which you are not member of

### Expected behaviour
Groups you are not member of should not appear in the dropdown

### Actual behaviour
ALL GROUPS are currently listed

**Comment by nickvergessen** [comment]
This is currently the expected behavior.
