### ISSUE TITLE
Any way to allow certain groups to post annoucements?

### ISSUE THREAD

**Issue by sbe-arg** [nextcloud/announcementcenter#863]
I cannot find any way to restrict who can create announcements.

**Comment by nickvergessen** [comment]
In the admin settings in the last category "Additional settings"

**Comment by sbe-arg** [comment]
Probably that section could be renamed a bit to reference that is part of the announcements app.

**Comment by nickvergessen** [comment]
It's a generic section from the server for all apps that only have very limited settings (like this one)
