### ISSUE TITLE
Image "announcementcenter-dark.svg" is ALWAYS delivered via an absolute URL over HTTP 

### ISSUE THREAD

**Issue by stephan-a** [nextcloud/announcementcenter#90]
The activity icon is delivered via an absolute URL over HTTP although the nextCloud instance is running over HTTPS. This leads to a Content Security Policy violation:
```
Refused to load the image 'http://domain.com/apps/announcementcenter/img/announcementcenter-dark.svg' because it violates the following Content Security Policy directive: "img-src 'self' data: blob:".
```
The HTTP header "X-Forwarded-Proto" is set to "https" and "overwriteprotocol" is set to "https" in config.php as well.

Is it really necessary to use an absolute URL here? Simply using a relative URL would fix this issue. The absolute URL is only needed in an e-mail notification.

### Requirements
The nextCloud instance must be running over HTTPS.

### Steps to reproduce
1. Publish a new announcement
2. Login with another user so the new announcement will appear in the activity popover in the header

### Expected behaviour
The image "announcementcenter-dark.svg" should get displayed in the announcement item in the header popover.

### Actual behaviour
- Instead of the image "announcementcenter-dark.svg" only a image placeholder is displayed in the announcement item in the header popover.
- There is an error message in the JavaScript console because of a Content Security Policy violation.

### Server configuration

**Operating system**: Ubuntu 16.04.3 LTS

**Web server:** Apache 2.4.18

**Database:** MySQL 5.7.20

**PHP version:** 7.0.22

**Nextcloud version:** 12.0.3

### Client configuration
**Browser:** Chrome 62.0.3202.75

#### Browser log
```
Refused to load the image 'http://domain.com/apps/announcementcenter/img/announcementcenter-dark.svg' because it violates the following Content Security Policy directive: "img-src 'self' data: blob:".
```

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/announcementcenter/blob/master/lib/Activity/Provider.php#L87-L89

We use the `getAbsoluteURL` method. Please make sure that your `overwrite.cli.url` is set correctly in the config.php

**Comment by stephan-a** [comment]
Ah, the issue only occurs with an announcement created in nextCloud v11.0.3. After upgrading to v12.0.3 the activity icon in the notification doesn't show up because of the wrong protocol.
With announcements created in nextCloud v12.0.3 everything is okay.

The `overwrite.cli.url` is set correctly in config.php.

**Comment by nickvergessen** [comment]
Ah right, yeah in 11 we created the links when creating the notification, so if you changed to SSL afterwards, those are still broken.

**Comment by zeigerpuppy** [comment]
There still seems to be an issue with this (v3.4.1).  When I install Announcement Centre, the icon `announcementcentre_dark.svg` is served over HTTP.  However, everything is over HTTPS and `overwrite.cli.url` is correctly set with https. Nextcloud V15.0.2

**Comment by dshastry** [comment]
+1 same issue here.
