### ISSUE TITLE
[NC13] Announcements are misaligned - since NC13 horizontally instead of vertically

### ISSUE THREAD

**Issue by Schmuuu** [nextcloud/announcementcenter#94]
### Steps to reproduce
1. Update Nextcloud to v13.0 stable
2. use Announcement Center app to post an announcement
3. see the announcement appear next to the input field but not down below as expected

### Expected behaviour
Announcements are provided in vertical alignment, like known from Nextcloud 12.0.4.

### Actual behaviour
Announcements are aligned horizontally in very narrow columns and are therefor difficult to read.

## Server configuration detail

**Operating system:** Linux 4.14.17-1-lts #1 SMP Sat Feb 3 21:30:38 CET 2018 x86_64

**Webserver:** nginx/1.12.2 (fpm-fcgi)

**Database:** mysql 10.1.30

**PHP version:** 7.2.2
Modules loaded: Core, date, libxml, openssl, pcre, zlib, ctype, dom, fileinfo, filter, hash, json, mbstring, pcntl, SPL, PDO, bz2, posix, readline, Reflection, session, SimpleXML, standard, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, cgi-fcgi, Phar, curl, exif, ftp, gd, gmp, intl, iconv, pdo_mysql, zip, apcu, memcache, Zend OPcache

**Nextcloud version:** 13.0.0 - 13.0.0.14

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from 12.0.5 

**Where did you install Nextcloud from:** Web Updater

<details><summary>Signing status</summary>

No errors have been found.
</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - activity: 2.6.1
 - admin_audit: 1.3.0
 - admin_notifications: 1.0.1
 - announcementcenter: 3.1.1
 - apporder: 0.4.1
 - audioplayer: 2.2.5
 - bookmarks: 0.10.1
 - bruteforcesettings: 1.0.3
 - calendar: 1.6.0
 - circles: 0.13.6
 - cms_pico: 0.9.7
 - comments: 1.3.0
 - contacts: 2.0.1
 - dav: 1.4.6
 - deck: 0.3.0
 - external: 3.0.2
 - federatedfilesharing: 1.3.1
 - federation: 1.3.0
 - files: 1.8.0
 - files_accesscontrol: 1.3.0
 - files_automatedtagging: 1.3.0
 - files_downloadactivity: 1.2.0
 - files_external: 1.4.1
 - files_markdown: 2.0.1
 - files_pdfviewer: 1.2.0
 - files_reader: 1.2.2
 - files_retention: 1.2.0
 - files_sharing: 1.5.0
 - files_texteditor: 2.5.1
 - files_trashbin: 1.3.0
 - files_versions: 1.6.0
 - files_videoplayer: 1.2.0
 - firstrunwizard: 2.2.1
 - gallery: 18.0.0
 - groupfolders: 1.2.0
 - issuetemplate: 0.3.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.1.0
 - mail: 0.7.9
 - metadata: 0.6.0
 - nextcloud_announcements: 1.2.0
 - notes: 2.3.2
 - notifications: 2.1.2
 - oauth2: 1.1.0
 - ojsxc: 3.3.2
 - onlyoffice: 1.2.0
 - password_policy: 1.3.0
 - polls: 0.8.1
 - provisioning_api: 1.3.0
 - quota_warning: 1.2.0
 - ransomware_protection: 1.1.0
 - serverinfo: 1.3.0
 - sharebymail: 1.3.0
 - socialsharing_email: 1.0.3
 - spreed: 3.0.1
 - systemtags: 1.3.0
 - telephoneprovider: 1.0.1
 - theming: 1.4.1
 - twofactor_backupcodes: 1.2.3
 - twofactor_totp: 1.4.1
 - updatenotification: 1.3.0
 - user_usage_report: 1.0.1
 - workflowengine: 1.3.0
Disabled:
 - checksum
 - drawio
 - encryption
 - impersonate
 - passman
 - sharerenamer
 - survey_client
 - tasks
 - user_external
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "my.domain.tld",
        "192.xxx.xx.xx",
        "localhost"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "version": "13.0.0.14",
    "logtimezone": "Europe\/Berlin",
    "appstore.experimental.enabled": true,
    "appstoreenabled": true,
    "appstoreurl": "https:\/\/api.nextcloud.com\/v1",
    "mail_smtpmode": "smtp",
    "mail_smtpauth": 1,
    "mail_smtpport": "587",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauthtype": "LOGIN",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpsecure": "tls",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
    "enabledPreviewProviders": [
        "OC\\Preview\\PNG",
        "OC\\Preview\\JPEG",
        "OC\\Preview\\GIF",
        "OC\\Preview\\BMP",
        "OC\\Preview\\XBitmap",
        "OC\\Preview\\MP3",
        "OC\\Preview\\TXT",
        "OC\\Preview\\MarkDown",
        "OC\\Preview\\TIFF"
    ],
    "filelocking.enabled": true,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 0,
        "timeout": 0,
        "dbindex": 0,
        "password": "***REMOVED SENSITIVE VALUE***"
    },
    "maintenance": false,
    "updater.server.url": "https:\/\/updates.nextcloud.com\/updater_server\/",
    "updater.release.channel": "stable",
    "loglevel": 2,
    "theme": "",
    "installed": true,
    "overwrite.cli.url": "https:\/\/my.domain.tld",
    "updater.secret": "***REMOVED SENSITIVE VALUE***"
}
```
</details>

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** None

## Client configuration

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0

**Operating system:** Windows 10

## Logs

Neither nextcloud.log nor browser console contains any relevant entries.

**Comment by Schmuuu** [comment]
Hi @nickvergessen @jancborchardt 

Could you look into this one. Might be a very little CSS bug, that's (hopefully) easy to fix.
Some Announcements have only one to three words per row and reading the text is no fun since NC13.
![announcement-center_blur2](https://user-images.githubusercontent.com/26191454/36093591-6907e970-0feb-11e8-9130-7798646d9ef1.jpg)

**Comment by nickvergessen** [comment]
display:flex; on app-content-wrapper is the problem.

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/announcementcenter/pull/96 Fixed it, will merge and release as soon as the tests pass

**Comment by nickvergessen** [comment]
Published https://apps.nextcloud.com/apps/announcementcenter/releases?platform=13#13
